### PR TITLE
Feature/android studio update

### PR DESCRIPTION
**Pull request by andredublin**
Update android studio .idea folder. Generally I tend to put the .idea folder in the gitignore so I'm not sure if we should merge this or we should just ignore the whole .idea folder.

### CODE REVIEW

**Comment by ktenzweiler** [comment]
I have usually ignored the whole .idea directory. I am pretty sure that whole directory is generated auto-magically when building the project.

**Comment by andredublin** [comment]
I propose we add the .idea folder to the .gitignore file and remove the .idea folder from source control, I can apply those changes in this repo if that's ok?

**Comment by andredublin** [comment]
I've updated the PR to remove .idea from source control and added .idea to the .gitignore file

**Comment by andredublin** [comment]
Looks to be autogenerated, I'm guessing backendless libraries

**Pull request merged**
