### PR TITLE
feature/Card-222

### PR DESCRIPTION
**Pull request by andredublin**
Gets the signed in users name and show in the nav drawer. It will replace the text Help A Paw with the users name if they are logged in.

### CODE REVIEW

**Comment by BurningAXE** [comment]
Hey Andre, 
I finally checked the PR. It works when you log in and out. However, when the user is logged and the app is restarted (e.g. killed by the OS and started again) the username is null. I think this is related to this Backendless "feature" (really a bug IMHO): https://support.backendless.com/t/userservice-currentuser-is-null-even-if-usertokenstoragefactory-retruns-token/3239/18
Can you try the fix suggested there?

**Comment by andredublin** [comment]
@BurningAXE will do

**Comment by andredublin** [comment]
@BurningAXE So i tested it out, your right it is a problem with backendless. The link you posted suggested we add `stayLoggedIn` however we already seem to be doing that see:

https://github.com/HelpAPaw/Android/blob/development/app/src/main/java/org/helpapaw/helpapaw/data/user/BackendlessUserManager.java#L33

and

https://github.com/HelpAPaw/Android/blob/development/app/src/main/java/org/helpapaw/helpapaw/data/user/BackendlessUserManager.java#L49

The boolean is the `stayLoggedIn` value.

I'll see if there is another way around this, but we may be in a situation where we will have to rely on backendless to fix their issue.

**Comment by BurningAXE** [comment]
@andredublin Yes, we already use that and indeed the user stays logged in but as far as I understand when we check (which is at app loading time) the currentUser object is not yet loaded. Not sure if this can be fixed by the SDK. There is a suggestion in this answer: https://support.backendless.com/t/userservice-currentuser-is-null-even-if-usertokenstoragefactory-retruns-token/3239/2
Can you try that?

**Comment by andredublin** [comment]
@BurningAXE that should do it now, tested it out and the user name is recovered properly after the app is killed

**Comment by BurningAXE** [comment]
Great! It works now. Merging it.

**Pull request merged**
