### PR TITLE
Feature/card 251

### PR DESCRIPTION
**Pull request by andredublin**
Bug fix for card:
https://helpapaw.kanbanize.com/ctrl_board/14/cards/251/details

How to reproduce bug
- Set OS font to a big value
- Create a signal and add some comments
- The date and author of the comment overlap

### Screenshots displaying fix for this bug
screenshot_20180726-131021
screenshot_20180726-131129

### CODE REVIEW

**Comment by BurningAXE** [comment]
Hey, is there an easy way to leave the username on the same line and make both TextViews expand in height without overlapping?

**Comment by andredublin** [comment]
@BurningAXE I'd have to research that, I'm currently not aware of a way to detect the systems font level/size.

**Comment by ktenzweiler** [comment]
Sorry for late reply. Under the res directory you could create a couple new directories: values-mdpi, values-hdpi, values-xdpi, values-xxdpi, values-xxxdpi; Then make a dimens.xml file in each of the new directories, then create a couple resources like smallText, mediumText, largeText, set them to 12sp, 14sp, 18sp for the mdpi and hdpi dimens.xml files,  Then for the dimens.xml files in the xdpi and xxdpi set the smallText, mediumText, and largeText to 14sp, 16sp, 20sp. Then for the xxxdpi dimens.xml file increase the text size 2 more. This is the best way I have dealt with multiple screen densities, without getting too granular. 
Here are the docs to doing this https://developer.android.com/guide/topics/resources/providing-resources

**Comment by BurningAXE** [comment]
I added some commits with a different layout that I think works good with different system font and screen sizes. Can you check it, too?

**Pull request merged**
