### PR TITLE
feature/Card-256

### PR DESCRIPTION
**Pull request by andredublin**
Adds the settings screen to save timeout and distance to be read from the maps view.

I had to update google play services from 15.0.1 => 16.0.0 it was no longer showing up in the google repository.

### CODE REVIEW

**Comment by BurningAXE** [comment]
:D Great, it works fine now!
If I may ask for just two more improvements 😇
1. Initially zoom the map to the currently selected radius setting so the user can see all obtained signals
2. If the users changes the zoom manually - get the signals for the currently shown map region. E.g. current radius setting is 10 km. but the user zooms out to 50 km. => get signals for the 50 km. map area currently shown

**Comment by andredublin** [comment]
Yeah I can do that, it'll be done by this weekend.

**Comment by andredublin** [comment]
@BurningAXE Applied the changes to update the search radius based on map zoom when the camera changes and also sets the initial map zoom to the saved radius from settings. However I don't believe that backendlless is honoring the query when the zoom changed, though I've verified that the zoom to meters calculation was correct. I imagine there must be a necessary update on backendless.

**Comment by BurningAXE** [comment]
@andredublin There's damping logic in SignalsMapPresenter:93 that resulted in not getting signals after every zoom change. Is this what concerns you?
If yes - I added a check for radius change and it works fine now. If not - what do you think is the problem?
I added some other small changes, too. Please review them.

**Comment by andredublin** [comment]
@BurningAXE yeah that looks to have solved the problem, thanks!

**Comment by BurningAXE** [comment]
Great! So we are done here! Great job!

**Pull request merged**
